name: Lint
on: [push]

jobs:
  yarn-lint:
    name: yarn lint
    runs-on: ubuntu-18.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: yarn
      run: yarn install --frozen-lockfile
    - name: lint
      run: yarn run lint
    - name: build:styles
      run: yarn run build:styles
