name: Deploy Docs
on:
  release:
     types: [published]
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: yarn
      run: yarn install --frozen-lockfile
    - name: build docs
      run: yarn build:eleventy
    - name: deploy docs to server
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET }}
        SOURCE: "dist/"
        ARGS: "-rltzv --delete"
